### ISSUE TITLE
Request: option to mutually nullify game’s result

### ISSUE THREAD

**Issue by elizaaverywilson** [lichess-org/lichess-source-code#1]
Hello lichess development community!

I often think it would be very useful to have an option for players to mutually agree to nullify the result after the game has started. There should be no change in rating, tournament standing, or player vs. player win loss record, and the nullification result should be displayed both on the game’s page and where the game appears on the player profile.

Sometimes a rated game begins and something goes wrong in real life that prevents the game’s result from being fair—for example, one player suddenly has to unavoidably, unexpectedly leave, or experienced connection issues. Of course, this would probably not be the favored option among strangers, but it can be very useful in tournaments or friends. Draws are not satisfactory solutions to this, because they benefit the lower-rated or lower-scoring. This should be an additional option, along with claiming victory or a draw for one player to choose from when the other player. It should also be something that regardless of abandonment, can be requested by one player, and then accepted by another, like a draw.

It might be also useful for tournament organizers to unilaterally put a tournament game into this status, but I’m not sure if that might cause abuse. Even if players mutually agreeing to do this was the only way, it would still be useful to add.

Thank you for reading my request, and all of your hard work!

**Comment by niklasf** [comment]
Sorry, this repository exists only to refer to https://github.com/ornicar/lila. Will disable issues, here.
